#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BNO055.h>

//#definir SWITCH_IZQUIERDO_PIN 29
#define PIN DE REFERENCIA DEL INTERRUPTOR 30
#define SWITCH_TRASERO_PIN 29

//................................ .......motores................ ..........................
#define INA1 7
#define INB1 8
#define PWM1 6

#define INA2 5
#define INB2 2
#define PWM2 3x

#define INA3 12
#define INB3 11
#define PWM3 4
#define START_BYTE 0xAA
//................................ .............................. ..........................

// Crear objeto del sensor
Adafruit_BNO055 bno = Adafruit_BNO055(55, 0x28);

error de flotación = 0;
corrección de flotación;
flotante inicialYaw = 0;
flotante initialPitch = 0;
flotante initialRoll = 0;
int cont = 0;
flotador kp = 2;
flotante vel0 = 100;

tiempoAnterior largo sin signo = 0;
int estado = 0;
bool enMovimiento = false;
unsigned long previousMillis = 0;
int estado1 = 0;
int esquina = 0;
int lectura = 0;
int codigo = 0;
int lectura1 = 0;
int esquive = 0;
configuración vacía() {
  retraso(1000);
  Serial.begin(115200);
  Serial1.begin(19200); 
  pinMode(INA1, SALIDA);
  pinMode(INB1, SALIDA);
  pinMode(PWM1, SALIDA);
  pinMode(INA2, SALIDA);
  pinMode(INB2, SALIDA);
  pinMode(PWM2, SALIDA);
  pinMode(INA3, SALIDA);
  pinMode(INB3, SALIDA);
  pinMode(PWM3, SALIDA);

  //pinMode(SWITCH_IZQUIERDO_PIN , INPUT_PULLUP);
  pinMode(INTERRUPTOR_DERECHO_PIN, ENTRADA_PULLUP);
  pinMode(INTERRUPTOR_TRASERO_PIN, ENTRADA_SUBIR);
  
  si (!bno.begin()) {
    Serial.println("¡No se pudo encontrar el BNO055!");
    mientras (1);
  }

  bno.setExtCrystalUse(verdadero);

  sensores_event_t evento;
  bno.getEvent(&evento);

  initialYaw = evento.orientacion.x;
  initialPitch = evento.orientacion.z;
  initialRoll = evento.orientacion.y;

  Serial.println("Orientación inicial:");
  Serial.print("Guiñada: "); Serial.println(inicialGuiñada);
  Serial.print("Paso: "); Serial.println(Paso inicial);
  Serial.print("Roll: "); Serial.println(initialRoll);
  Serial.println("-------------- ------------");
}
void a() { 

  escritura digital (INA3, 0);
  escritura digital (INB3, 1);
  analogWrite(PWM3, 170);

  escritura digital (INA2, 1);
  escritura digital (INB2, 0);
  analogWrite(PWM2, 170);

  escritura digital (INA1, 0);
  escritura digital (INB1, 0);
  analogWrite(PWM1, 0);
}
vacío ai() {
  escritura digital (INA3, 1);
  escritura digital (INB3, 0);
  analogWrite(PWM3, 60);

  escritura digital (INA2, 1);
  escritura digital (INB2, 0);
  analogWrite(PWM2, 60);

  escritura digital (INA1, 0);
  escritura digital (INB1, 1);
  analogWrite(PWM1, 103);
}

anuncio vacío() {
  escritura digital (INA3, 0);
  escritura digital (INB3, 1);
  analogWrite(PWM3, 60);

  escritura digital (INA2, 0);
  escritura digital (INB2, 1);
  analogWrite(PWM2, 60);

  escritura digital (INA1, 1);
  escritura digital (INB1, 0);
  analogWrite(PWM1, 96.4);
}

void pare() {
  escritura digital (INA3, 0);
  escritura digital (INB3, 1);
  analogWrite(PWM3, 0);

  escritura digital (INA2, 0);
  escritura digital (INB2, 1);
  analogWrite(PWM2, 0);

  escritura digital (INA1, 1);
  escritura digital (INB1, 0);
  analogWrite(PWM1, 0);
}

vacío r() {
  escritura digital (INA3, 1);
  escritura digital (INB3, 0);
  analogWrite(PWM3, 170);

  escritura digital (INA2, 0);
  escritura digital (INB2, 1);
  analogWrite(PWM2, 170);

  escritura digital (INA1, 0);
  escritura digital (INB1, 0);
  analogWrite(PWM1, 0);
}
vacío gd(){
 escritura digital (INA1, ALTA);
 escritura digital (INB1, BAJO);
 escritura analógica(PWM1, 45); // Velocidad (0-255) señal pwm
 escritura digital (INA2, ALTA);
 escritura digital (INB2, BAJO);
 analogWrite(PWM2, 0);
 escritura digital (INA3, ALTA);
 escritura digital (INB3, BAJO);
 analogWrite(PWM3, 0);  
 }
 vacío gi(){
 escritura digital (INA1, BAJO);
 digitalWrite(INB1, ALTO);
 escritura analógica(PWM1, 45); // Velocidad (0-255) señal pwm
 escritura digital (INA2, BAJO);
 escritura digital (INB2, ALTA);
 analogWrite(PWM2, 0);
 escritura digital (INA3, BAJO);
 escritura digital (INB3, ALTA);
 analogWrite(PWM3, 0);  
 }
vacío ggd(){
 escritura digital (INA1, ALTA);
 escritura digital (INB1, BAJO);
 escritura analógica(PWM1, 45); // Velocidad (0-255) señal pwm
 escritura digital (INA2, ALTA);
 escritura digital (INB2, BAJO);
 analogWrite(PWM2, 45);
 escritura digital (INA3, ALTA);
 escritura digital (INB3, BAJO);
 analogWrite(PWM3, 45);  
 }
 vacío ggi(){
 escritura digital (INA1, BAJO);
 digitalWrite(INB1, ALTO);
 escritura analógica(PWM1, 45); // Velocidad (0-255) señal pwm
 escritura digital (INA2, BAJO);
 escritura digital (INB2, ALTA);
 analogWrite(PWM2, 45);
 escritura digital (INA3, BAJO);
 escritura digital (INB3, ALTA);
 analogWrite(PWM3, 45);  
 }
vacío leerbytes() {
  enumeración estática { ESPERA_INICIO, ESPERA_DURACIÓN, ESPERA_DATOS } lectura = ESPERA_INICIO;
  buffer de bytes estáticos[10];
  longitud de byte estático = 0;
  índice de byte estático = 0;
   
   
  mientras (Serial1.disponible()) {
    byte b = Serial1.read();
    //Serial.println("Iniv");
    //Serial.print("Iniv");
    interruptor (lectura) {
      caso WAIT_START:
        si (b == START_BYTE) {
          lectura = DURACIÓN_DE_ESPERA;
        }
        romper;

      caso DURACIÓN_DE_ESPERA:
        longitud = b;
        índice = 0;
        lectura = ESPERA_DATOS;
        romper;

      caso WAIT_DATA:
        buffer[índice++] = b;
        if (index >= length + 1) { // +1 para la suma de comprobación
          // Verificar suma de comprobación
          suma de comprobación de bytes = 0;
          para (int i = 0; i < longitud; i++) suma de comprobación += buffer[i];
          suma de comprobación %= 256;

          si (suma de comprobación == buffer[longitud]) {
            // Datos válidos
            byte codigo = buffer[0];//le llega el color
            byte x = buffer[1];
            byte y = buffer[2];

            Serial.print("OK -> Código: ");
            Serial.print(codigo);
            Serial.print(", X: ");
            Serie.print(x);
            Serial.print(", Y: ");
            Serial.println(y);
            Serial.println("Suma de comprobación incorrecta");

          }
          lectura = WAIT_START; // Reiniciar estado
        }
        romper;
    }
bucle vacío() {
        sensores_event_t evento;
        bno.getEvent(&evento);

        float currentYaw = evento.orientacion.x;
        float currentPitch = evento.orientacion.z;
        float currentRoll = evento.orientacion.y;

     si (guiñada actual > 180){
       actualYaw = actualYaw - 360;
       }
        error = yaw inicial - yaw actual;
        float correcion=-error*kp;
        si(error < -180)
        {
         error = error + 360;
        }
      
  unsigned long currentMillis = millis();

  bool switchDerechoActivado = digitalRead(SWITCH_DERECHO_PIN ) == LOW;
  bool switchTraseroActivado = digitalRead(SWITCH_TRASERO_PIN ) == LOW;
  //bool switchIzquierdoActivado = digitalRead(SWITCH_IZQUIERDO_PIN ) == LOW; 

  cambiar (estado) {
    caso 0:
      //si (!enMovimiento) {  
        anuncio();
       // enMovimiento = true;
       //Millis anterior = Millis actual;
      //}
      si (switchDerechoActivado == 1) {
        cortar();
        //enMovimiento = false;
        estado = 1;
        anteriorMillis = actualMillis;
      }
       Serial.println (estado);
      romper;

    caso 1:
      si (error < -180) {
       error = error + 360;
      }
      si (error > 7) {
       soldado americano();
      }
      de lo contrario si (error < -7) {
       gd();
      }
      demás {  
        leerbytes();
        si (codigo == 2){
        esquivar = 0;
        }
        a();}
        si (currentRoll > 6.50){
          cortar();
        //enMovimiento = false;
        anteriorMillis = actualMillis;
         estado = 2; 
        }
       }
        Serial.println (estado);
    break; // <-- ¡Importante!
    
    caso 2:
    si (error < -180) {
       error = error + 360;
      }
      si (error > 7) {
       soldado americano();
      }
      de lo contrario si (error < -7) {
       gd();
      }
      demás {  
    ai(); // ejecutar movimiento constantemente
      }
    si (Millis actual - Millis anterior >= 1300) { 
        cortar();             
        estado = 3;        
        anteriorMillis = actualMillis;
    }
     Serial.println (estado);
    romper;

    caso 3:
 si (error < -180) {
       error = error + 360;
      }
     si (error > 7) {
      soldado americano();
    }
    de lo contrario si (error < -7) {
      gd();
    }
    demás {
       r();                
    }
   si (switchTraseroActivado == 0) {
        cortar();
         estado = 8; 
         anteriorMillis = actualMillis;
       }
        Serial.println (estado);
      romper; 
    caso 8:
      anuncio();
      si(Millis actual - Millis anterior >= 300){
        cortar();
      estado = 9;
      anteriorMillis = actualMillis; 
      }
       Serial.println (estado);
      romper;
    caso 9:
    si (error < -180) {
       error = error + 360;
      }
     si (error > 7) {
      soldado americano();
    }
    de lo contrario si (error < -7) {
      gd();
    }
    demás {
      si (codigo == 2){
        esquivar = 1;
      }
     a();}
     si (currentRoll > 6.50){
      cortar();
      estado = 11;
      anteriorMillis = actualMillis;
     }
      Serial.println (estado);
       romper;
    caso 11:
    ai();
    si(Millis actual - Millis anterior >= 650){
      cortar();
      estado = 12;
      anteriorMillis = actualMillis; 
      }
       Serial.println (estado);
      romper;
    caso 12:
     si (error < -180) {
       error = error + 360;
      }
     si (error > 7) {
      soldado americano();
    }
    de lo contrario si (error < -7) {
      gd();
    }
    demás {
    r();}
    si (switchTraseroActivado == 0) {
        cortar();
        estado = 13;
        }
         Serial.println (estado);
        romper;
    caso 13:
    interruptor (esquina){
    caso 0: 
    anuncio();
    si (switchDerechoActivado == 1) {
        cortar();
        esquina = 1;
        anteriorMillis = actualMillis;
        }
         Serial.println (esquina);
        romper;
    caso 1 :
    ai();
    si(Millis actual - Millis anterior >= 150){
    cortar();
    esquina = 2;
    anteriorMillis = actualMillis; }
       Serial.println (esquina);
    romper;

    caso 2:
    ggi();
    si(Millis actual - Millis anterior >= 250){
    cortar();
    esquina = 3;
    anteriorMillis = actualMillis; }
      Serial.println (esquina);
    romper;
    caso 3:
    gd();
    si(Millis actual - Millis anterior >= 250){
    cortar();
    esquina = 4;
    anteriorMillis = actualMillis; }
      Serial.println (esquina);
    romper;
    caso 4:
     si (error < -180) {
       error = error + 360;
      }
     si (error > 7) {
      soldado americano();
    }
    de lo contrario si (error < -7) {
      gd();
    }
    demás {
    r();}
    si (switchTraseroActivado == 0) {
        cortar();
        estado = 1;
        esquina = 0;
        anteriorMillis = actualMillis;
    }
      Serial.println (esquina);
    romper;
    cambiar(esquivar){
      caso 0:
      ai();
      si (Millis actual - Millis anterior >= 500){
        estado = 1;
        anteriorMillis = actualMillis;
      }
      romper;
      caso 1:
      gd();
      si (Millis actual - Millis anterior >= 100){
        soldado americano();}
        si (Millis actual - Millis anterior >= 100){
      anuncio();}
      si (switchDerechoActivado == 1){
      estado = 1;
      }
      romper;

    }
    
    }}
}
